image: "fpco/stack-build:lts"

stages:
    - test

variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

build:
    stage: "test"
    only:
        - master
    cache:
        key: "$CI_BUILD_NAME"
        paths:
            - .stack-work/
            - .stack-root/
    script:
        - stack test --ghc-options -Werror --test-arguments="--qc-max-success=10000"
