image: "fpco/stack-build"

stages:
    - test

variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

build:
    stage: "test"  
    cache:
        key: "$CI_BUILD_NAME"
        paths:
            - .stack-work/
            - .stack-root/
    script:
        - stack test --ghc-options -Werror --test-arguments=--junit-output > test-report.xml
    artifacts:
        reports:
            junit: test-report.xml
    
