#+TITLE: The Kima programming language
#+AUTHOR: Michail Pardalos
#+EMAIL: mpardalos@gmail.com

* Semantics
** Types
In Kima there are two kinds of types:
*** Builtins
These include:
+ Ints
+ Floats
+ Strings
+ Bools
+ Unit
+ Functions
Functions are so far the only parameterized type. A function type is
parameterized by its argument types and return type.

*** User-defined types
These are defined using the ~data~ keyword, and are non-parametric. Types of
this kind are solely defined by their name. 

** Closures
A function captures all bindings available when it is created.
Note, that in the case of 
In addition, if it is a named function, then it also captures itself.

** Effects
Every function in Kima, in addition to its argument and return types, has an
effect type. This determines what kind of side effects the function is allowed
to perform.

Each effect defines a set of ~procedures~ that may be used inside functions
annotated with that effect.

Effects can then be **handled** by the ~handle~ construct. This allows an
effectful function to be called inside a context that doesn't support its
effect, by giving a handler for that effect within the calling context.

The handlers receive an implicit ~resume~ argument. This is the delimited
continuation at the call site of the procedure. This can be called with the
return type of the procedure to

# For example, the ~console~ can be handled inside a pure context by making the
# input procedure always return the same string and storing the results of the
# output procedure.


* Syntax -- Out of date
** Data definitions
There are two kinds of data definitions.
*** Records
A record definition has the following structure:
#+BEGIN_SRC
data NAME (
    NAME_1: mut TYPE_1,
    NAME_2: TYPE_2,
    ...
    NAME_N: TYPE_N,
);
#+END_SRC
It defines a user type ~NAME~ along with the following:
+ A constructor \\
  ~{NAME} : (TYPE_1, ..., TYPE_N) -> NAME~
+ Accessors\\
  ~{.NAME_1} : (NAME) -> TYPE_1~\\
  ~{.NAME_2} : (NAME) -> TYPE_2~\\
  ...\\
  ~{.NAME_N} : (NAME) -> TYPE_N~
+ Setters\\

*** Enums
An enum declaration has the following form:
#+BEGIN_SRC
data NAME {
    CONSTRUCTOR_1(ARG_11, ARG_12, ..., ARG_1N),
    CONSTRUCTOR_2(ARG_21, ARG_22, ..., ARG_2N),
    ... ,
    CONSTRUCTOR_M(ARG_M1, ARG_M2, ..., ARG_MN),
};
#+END_SRC
It defines a user type ~NAME~ along with constructors:\\
  ~{CONSTRUCTOR_1} : (ARG_1, ..., ARG_N) -> NAME~\\
  ...\\
  ~{CONSTRUCTOR_M} : (ARG_1, ..., ARG_N) -> NAME~\\

** Pattern matching
Pattern matching is done through a ~case~ expression.
#+BEGIN_SRC
data Event {
    Click(Button, Pos),
    KeyPress(Char),
    Quit
};

fun what_event(ev: Event) -> String {
    case ev {
        Click(btn, pos) { btn + " click" }
        KeyPress(btn)   { "key " + btn   }
        Quit            { "quit"         }
    }
}
#+END_SRC

Incomplete patterns are an error.
** Accessors
Accessors allow reading and mutating record fields.
They have the form `EXPRESSION . IDENTIFIER`.
Any accessor of this form may be used for reading. To be used for mutating,
the object refered to be the expression must have mutable type, and its
IDENTIFIER field must also be mutable.
